import './globals.css';
import "react-loading-skeleton/dist/skeleton.css";;
import type { Metadata } from 'next'
import Link from 'next/link'
import { Providers } from './providers'
import { authOptions } from '../shared/lib';
import { getServerSession } from 'next-auth';
import { Header } from '../widgets/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)


  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Kalkulator Kkal</title>
        <meta name="description" content="Онлайн калькулятор калорий и учет приемов пищи. Следите за своим рационом и достигайте своих целей." />
        <meta name="keywords" content="калории, калькулятор, учет приемов пищи, здоровое питание" />
        <meta httpEquiv="Content-Language" content="ru" />
        <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta property="og:title" content="Kalkulator Kkal" />
        <meta property="og:description" content="Онлайн калькулятор калорий и учет приемов пищи. Следите за своим рационом и достигайте своих целей." />
        <meta property="og:image" content="ссылка на изображение вашего сайта" />
        <meta property="og:url" content="ссылка на ваш сайт" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&family=Unbounded:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-[#f5f5f5]">
        <Providers session={session}>
          <Header />
          {children}
        </Providers>

      </body>
    </html>
  )
}
